### ISSUE TITLE
Need a better README

### ISSUE THREAD

**Issue by brunj7** [NCEAS/scicomptasks#4]
We should add more descriptions to the README to include:
- More information about the purpose of this repo
- Help to navigate the repo content
- Guidelines on how to contribute

**Comment by njlyon0** [comment]
Added content for all three of these bullets to this commit: https://github.com/NCEAS/scicomptasks/commit/c459ee99f08d0cd5349012cb93275e2f0be441bb

Feel free to suggest other improvements or (if preferred) edit as needed!
